# Données carroyées

Les [données carroyées](https://www.insee.fr/fr/statistiques/2520034#titre-bloc-5) sont des données économiques agrégées sur tout le territoire français sur des carrés de 200m de côtés.

In [1]:
from jyquickhelper import add_notebook_menu
add_notebook_menu()

## Département de la réunion

Le code suivant utilise les données de la réunion disponible sur le site de l'INSEE : [Données carroyées à 200 mètres](https://www.insee.fr/fr/statistiques/2520034). Voir aussi la fonction [load_carreau_from_zip](https://github.com/sdpython/papierstat/blob/master/src/papierstat/datasets/carreau.py#L184) et aussi la fonction [from_file](http://geopandas.org/reference.html?highlight=from_file#GeoDataFrame.from_file) du module [geopandas](http://geopandas.org/index.html).

In [2]:
from papierstat.datasets import load_carreau_from_zip
dfcar, shpcar, dfrect, shprect = load_carreau_from_zip()

In [3]:
dfcar.head()

,id,idINSPIRE,idk,ind_c,nbcar
0,UTM40S200M_N38171E01797,CRS2975RES200mN7634200E0359400,N38171E01797-N38172E01797,16.0,2.0
1,UTM40S200M_N38172E01779,CRS2975RES200mN7634400E0355800,N38172E01779-N38172E01779,40.0,1.0
2,UTM40S200M_N38172E01780,CRS2975RES200mN7634400E0356000,N38172E01780-N38172E01780,64.0,1.0
3,UTM40S200M_N38172E01781,CRS2975RES200mN7634400E0356200,N38172E01781-N38172E01782,106.0,2.0
4,UTM40S200M_N38172E01782,CRS2975RES200mN7634400E0356400,N38172E01781-N38172E01782,6.0,2.0

In [4]:
shpcar.head()

,idINSPIRE,id,geometry
0,CRS2975RES200mN7634200E0359400,UTM40S200M_N38171E01797,"POLYGON ((359400 7634200, 359600 7634200, 3596..."
1,CRS2975RES200mN7634400E0355800,UTM40S200M_N38172E01779,"POLYGON ((355800 7634400, 356000 7634400, 3560..."
2,CRS2975RES200mN7634400E0356000,UTM40S200M_N38172E01780,"POLYGON ((356000 7634400, 356200 7634400, 3562..."
3,CRS2975RES200mN7634400E0356200,UTM40S200M_N38172E01781,"POLYGON ((356200 7634400, 356400 7634400, 3564..."
4,CRS2975RES200mN7634400E0356400,UTM40S200M_N38172E01782,"POLYGON ((356400 7634400, 356600 7634400, 3566..."

## Première carte